apiVersion: v2
name: leantime
description: Lean project management system for innovators
type: application
version: 1.2.3
appVersion: 3.3.3
keywords:
  - project management
  - task management
  - agile
  - kanban
  - lean
  - scrum
home: https://leantime.io/
sources:
  - https://github.com/Leantime/leantime
maintainers:
  - name: Matthew Blau
    email: matthew@rmblau.com
icon: https://raw.githubusercontent.com/Leantime/leantime/master/public/images/icon-192.png