{{- if and .Values.sessionstorage.enabled (not .Values.sessionstorage.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "leantime.fullname" . }}-sessions
spec:
  accessModes:
    - {{ .Values.sessionstorage.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.sessionstorage.size | quote }}
  {{- if .Values.sessionstorage.storageClass }}
  storageClassName: {{ .Values.sessionstorage.storageClass | quote }}
  {{- end }}
{{- end -}}